### PR TITLE
Used Enums for Filtering. Also added a Html extension to build Select Lists from Enum Values

### PR DESCRIPTION
**Pull request by PeterKneale**
The filtering is now performed using an enum

```
IPagedList<Group> GetGroups(string userId, GroupFilter filter, Page page);
```

The View model maintains the current filter

```
public class GroupsPageViewModel
{
   public IPagedList<GroupsItemViewModel> GroupList { get; set; }
   public GroupFilter Filter { get; set; }
}
```

The dropdown list is built automatically.

```
@Html.EnumDropDownListFor(model => model.Filter, new { @onchange = "LoadGroups();" })
```

### CODE REVIEW

**Comment by shijuvar** [comment]
Thanks @PeterKneale for this pull request.

**Comment by wmlockhart** [comment]
Hi @PeterKneale

I'm trying to use this excellent code for the base of a new app, however, I get the following error:

The call is ambiguous between:

'Oberhofen.EdNow.Web.Core.Extensions.SelectExtensions.EnumDropDownListFor<Oberhofen.EdNow.Web.ViewModels.GroupsPageViewModel,Oberhofen.EdNow.Service.GroupFilter>

and

'System.Web.Mvc.Html.SelectExtensions.EnumDropDownListFor<Oberhofen.EdNow.Web.ViewModels.GroupsPageViewModel,Oberhofen.EdNow.Service.GroupFilter>

on line 12:

@Html.EnumDropDownListFor(model => model.Filter, new { @onchange = "LoadGroups();" })

in file:

Views\Group\ListOfGroups.cshtml

Am I doing something wrong here? Please help.

Kind Regards

Walter

**Comment by wmlockhart** [comment]
Hi @PeterKneale

This is the complete error message:

Compiler Error Message: CS0121: The call is ambiguous between the following methods or properties: 'Oberhofen.EdNow.Web.Core.Extensions.SelectExtensions.EnumDropDownListFor<Oberhofen.EdNow.Web.ViewModels.GroupsPageViewModel,Oberhofen.EdNow.Service.GroupFilter>(System.Web.Mvc.HtmlHelper<Oberhofen.EdNow.Web.ViewModels.GroupsPageViewModel>, System.Linq.Expressions.Expression<System.Func<Oberhofen.EdNow.Web.ViewModels.GroupsPageViewModel,Oberhofen.EdNow.Service.GroupFilter>>, object)' and 'System.Web.Mvc.Html.SelectExtensions.EnumDropDownListFor<Oberhofen.EdNow.Web.ViewModels.GroupsPageViewModel,Oberhofen.EdNow.Service.GroupFilter>(System.Web.Mvc.HtmlHelper<Oberhofen.EdNow.Web.ViewModels.GroupsPageViewModel>, System.Linq.Expressions.Expression<System.Func<Oberhofen.EdNow.Web.ViewModels.GroupsPageViewModel,Oberhofen.EdNow.Service.GroupFilter>>, object)'

Kind Regards

Walter

**Comment by PeterKneale** [comment]
Are you using a newer version of mvc perhaps?
http://www.asp.net/mvc/overview/releases/mvc51-release-notes
There is now an extension method of the same name,"enumdropdownlistfor" in
the mvc framework which is why you may be getting the ambiguous reference
error.
Not on a pc at the moment so but hard to check but I think that may be your
error.
Cheers
Pete

**Comment by wmlockhart** [comment]
Thank you Peter for your quick response.

You are absolutely correct, I was using a version > 5.0

Are you guys planning any further releases in the near future of this excellent project?

Kind Regards

Walter

**Comment by PeterKneale** [comment]
Not sure about this project, i just contributed a few things I thought it might need. 
I've started my own here [utopia](https://github.com/Simplicate/Utopia) but its got a long way to go.

**Comment by wmlockhart** [comment]
Thanks Peter. It looks promising. Do you have a development plan or are you just trying to fit in when you have space?

**Pull request merged**
